[package]
name = "hax-phase-debug-webapp"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
edition.workspace = true
repository.workspace = true
readme.workspace = true

[lib]

[dependencies]
tiny_http = "0.12"
