name: Generate files on merge

on:
  pull_request_target:
    types:
      - closed
    branches:
      - master

jobs:
  generate_file:
    if: "github.event.pull_request.merged == true"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          cargo clean
          cargo build --verbose
          cargo install --path language
          cd examples
          cargo clean
          cargo build --verbose
          cargo hacspec -e v --dir ../coq/src/ --vc-dir ../coq/ --vc-update "*"
          # cargo hacspec -e fst --dir ../fstar/src/ --vc-dir ../fstar/ --vc-update "*"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Add generated files
          add-paths: |
            coq/src/*.v
            coq/_vc/*.v
          branch-suffix: timestamp
          base: master
          title: '[Examples] Add generated files'
          body: 'This PR is auto-generated by .github/workflows/generate_files.yml'
          labels: automated pr
