[package]
name = "hax-adt-into"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
edition.workspace = true
repository.workspace = true
readme.workspace = true
description = "Provides the `adt_into` procedural macro, allowing for mirroring data types with small variations."

[lib]
proc-macro = true

[dependencies]
itertools.workspace = true
syn.workspace = true
proc-macro2 = "1.0"
quote = "1.0"

[dev-dependencies]
tracing.workspace = true
